### ISSUE TITLE
RSS feed for blog

### ISSUE THREAD

**Issue by nihaals** [kaylynn234/website#1]

**Comment by redgoldlace** [comment]
I'm a bit late now, but this is fixed in #132b46f. I haven't tested it with any sort of real RSS reader (as I don't use RSS myself) but W3C's validator says it's okay. The changes have been deployed and you can consume the feed [here](https://kaylynn.gay/blog/feed.rss). There's also a note about it on the top-level blog page, so hopefully nobody misses it.
